packaging_format = 2

id = "invoiceninja5"
name = "InvoiceNinja 5"
description.en = "Create and email invoices, track payments, expenses, and time tasks"
description.fr = "Créer et envoyer des factures par e-mail, suivre les paiements, les dépenses et les tâches horaires"

version = "5.5.124~ynh1"

maintainers = ["Sebastian Gumprich"]

[upstream]
license = "Elastic-2.0"
website = "https://invoiceninja.org"
demo = "https://app.invoiceninja.com/dashboard"
admindoc = "https://invoiceninja.github.io/"
userdoc = "https://invoiceninja.github.io/"
code = "https://github.com/invoiceninja/invoiceninja"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/invoiceninja/invoiceninja/releases/download/v5.5.124/invoiceninja.zip"
        sha256 = "484b2a927a2249d7707ad96c5fa44b61d8daa0b7a052aaf13421dee1e6ff6fc7"
        in_subdir = false
        autoupdate.strategy = "latest_github_tag"
        rename = "invoiceninja.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.1-bcmath php8.1-gmp php8.1-fileinfo php8.1-gd php8.1-mbstring php8.1-pdo php8.1-xml php8.1-curl php8.1-zip php8.1-mysql libnss3-dev libatk1.0-0 libatk-bridge2.0-0 libxcomposite1 libxrandr2 libasound2"

    [resources.database]
    type = "mysql"
